#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2022 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import sys

import gi
gi.require_version('GMime', '3.0')
from gi.repository import GMime
GMime.init()

def main():
    ap = argparse.ArgumentParser(usage='%(prog)s < FILE')
    ap.parse_args()
    if sys.stdin.isatty():
        ap.error('stdin is a tty')
    istream = GMime.StreamPipe.new(sys.stdin.fileno())
    parser = GMime.Parser.new_with_stream(istream)
    msg = parser.construct_message()
    constr_7bit = getattr(GMime.EncodingConstraint, '7BIT');  # eww, FIXME
    msg.encode(constr_7bit)
    ostream = GMime.StreamPipe.new(sys.stdout.fileno())
    ostream = GMime.StreamFilter.new(ostream)
    from_filter = GMime.FilterFrom.new(GMime.FilterFromMode.ARMOR)
    ostream.add(from_filter)
    msg.write_to_stream(None, ostream)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
